=begin
Titan API

The ultimate, language agnostic, container based job processing framework.

OpenAPI spec version: 0.2.17

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for IronTitan::ImagesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ImagesApi' do
  before do
    # run before each test
    @instance = IronTitan::ImagesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ImagesApi' do
    it 'should create an instact of ImagesApi' do
      @instance.should be_a(IronTitan::ImagesApi)
    end
  end

  # unit tests for image_id_get
  # Get information for image id.
  # This gives more details about on image, such as the image name and other statistics.
  # @param id ID of the image.
  # @param [Hash] opts the optional parameters
  # @return [ImageWrapper]
  describe 'image_id_get test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for images_get
  # Get all image names.
  # TODO: Using images for lack of a better term. See https://github.com/iron-io/titan/issues/43 for discussion.
  # @param [Hash] opts the optional parameters
  # @return [ImagesWrapper]
  describe 'images_get test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
