=begin
Titan API

The ultimate, language agnostic, container based job processing framework.

OpenAPI spec version: 0.2.7

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for IronTitan::ErrorBody
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ErrorBody' do
  before do
    # run before each test
    @instance = IronTitan::ErrorBody.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ErrorBody' do
    it 'should create an instact of ErrorBody' do
      @instance.should be_a(IronTitan::ErrorBody) 
    end
  end
  describe 'test attribute "message"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "fields"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

