=begin
Titan API

The ultimate, language agnostic, container based job processing framework.

OpenAPI spec version: 0.0.4

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for IronTitan::
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Log' do
  before do
    # run before each test
    @instance = IronTitan::Log.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Log' do
    it 'should create an instact of Log' do
      @instance.should be_a(IronTitan::Log) 
    end
  end
  describe 'test attribute "log"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

