=begin
Titan API

The ultimate, language agnostic, container based job processing framework.

OpenAPI spec version: 0.3.10

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for IronTitan::Start
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Start' do
  before do
    # run before each test
    @instance = IronTitan::Start.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Start' do
    it 'should create an instact of Start' do
      @instance.should be_a(IronTitan::Start) 
    end
  end
  describe 'test attribute "started_at"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

