=begin
Titan API

The ultimate, language agnostic, container based job processing framework.

OpenAPI spec version: 0.0.2

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

module IronTitan
  VERSION = "0.0.2"
end
